### ISSUE TITLE
Add sorting of products on shoppinglist

### ISSUE THREAD

**Issue by susch19** [susch19/nssl#7]
Some people would like to sort the shopping items afterwards, so you can organize them, before you go out shopping. 
At first maybe not synchronize this between devices, but later this could be toggleable feature.

**Comment by TheBlubb14** [comment]
Made a pullrequest for that :) #8

**Comment by susch19** [comment]
Will stay open, till i'm satisfied with the result. It generally works, but the ui need some work.
For example, when in reordering mode, you shouldn't be able to change the list, the 3 dots in the top right should be hidden, adding scanning and searching should be hidden and a FAB Button with a Check Icon in it should be displayed to accept the reordering.
Maybe even hide the crossed out items, because they can't be reordered by design
